---
author: Andrew M. Demetriou
---

```{r}
# setup
library(here)
library(tidyverse)

values <- c("POWER", "ACHIEVEMENT", "HEDONISM", 
            "STIMULATION", "SELF", "UNIVERSALISM", 
            "BENEVOLENCE", "TRADITION", "CONFORMITY", 
            "SECURITY")
```

```{r}
# import data and initial format
speech_df <- readRDS(here("_data", "_primary_data", "speech_df.RDS")) |> 
  rename(item_ID = id, president_party = party) |>
  mutate(president = case_when(
    president == "Donald J. Trump (1st Term)" ~ "Donald J. Trump", 
    president == "William Howard Taft" ~ "William H. Taft", 
    .default = president))

participant_df <- readRDS(here("_data", "_participant_scores", "wave_2", "wave_2_dfs.RDS")) |> 
  bind_rows() |> 
  filter(! item_ID == "attention") |>
  select(item_ID, participant_ID, all_of(values), 
         c, w, Ethnicity, `Political spectrum (us)`) |>
  rename(confidence = c, percieved_party = w, 
         participant_party = `Political spectrum (us)`) |>
  mutate(confidence = factor(confidence, 
     levels = c(
        "Completely Unconfident",
        "Somewhat Unconfident",
        "Neither Confident nor Unconfident",
        "Somewhat Confident",
        "Completely Confident"),
      labels = c(
        "Unconfident (High)",
        "Unconfident (Low)",
        "Neutral",
        "Confident (Low)",
        "Confident (High)"),
      ordered = TRUE))
```

```{r}
# merge data
df <- participant_df %>%
  left_join(speech_df, by = "item_ID")

rm(participant_df, speech_df)
```

```{r}
# pivot data
df <- df |> pivot_longer(cols = all_of(values), values_to = "rating", names_to = "value")
```


```{r}
#knitr::purl("format_data.rmd", output = here("src", "format_data.R"))
```

